### ISSUE TITLE
开发历史文档：CheckList 20240815

### ISSUE THREAD

**Issue by ldbds** [ldbds/TempCDN#3]
# CheckList 20240915
开发历史文档 ，Checked at 20240930

## 未完成特性 
 - [ ] 配置参数掉电存储
 - [x] 文件高速传输（已实现）
 - [x] SystemView 系统调试
 - [ ] log.txt 系统日志
 - [ ] U盘读取
 - [ ] 6轴数据连接与上传
 - [x] LED灯逻辑与旧dragy匹配（已实现）
 - [ ] 蓝牙自动化测试Pattern
 - [ ] 量产SOP

## 未处理BUG
 - [x] 手机与oled显示数据不一致，高度比实际高2m，有时显示65535（修改为浮点数显示，确认可显示负数）
 - [x] 手机与oled显示数据不一致，速度显示有误差（修改为浮点数显示）
 - [x] I2C通讯可能卡死
 - [x] 下行数据时显示屏闪烁

## 新发现BUG
 - [x] GPS热启动未生效( 去除GPS Reset， V9 硬件遗漏 V8 修订)
 - [x] 文件异常删除 （test2.txt 用于调试全片擦除，已去除该调试功能）
 - [x] 存储状态无法获取 （可以通过获取cmd_start_record的值，判断是否有存储命令被挂起）
 - [x] 重新上电存储不了文件 （存储器上电默认读保护，需要解锁）
 - [x] 最大速度单位显示不对 (已修订)
 - [x] 概率性出现GPS电源不上电卡死 （增加独立看门狗）
 - [x] 充电过热无法开机（未复现，问题设备oled端子失效）
 - [ ] 不接电池仅用USB充电，频繁切换充电状态导致死机（未稳定复现）
 - [ ] 出现屏幕卡死后，蓝牙也搜索不到（未稳定复现）
 - [ ] OTA中途断开蓝牙连接，卡在OTA画面
 - [x] 删除所有文件”ALL“总是回复NCK(已修订)
 - [x] V8硬件校准后的GPS天线在V9硬件上信号差（单个设备，无法复现）

## 等待测试的BUGFIX
 - [ ] 开启存储后，实时数据传输是否丢包？
 - [ ] 电池循环测试，电量校准
 - [x] EH-MC25B 外部蓝牙天线信号强度（50~70m，略差于MC17）

## 未进行的风险项测试
 - [x] Ellisys蓝牙报文记录测试
 - [x] 直接断电文件可能丢失 (目录备份功能未实现， 增加低电压检测，断电前停止存储)

## 新需求
 - [x] LED灯逻辑增加记录状态(已修订)
 - [x] dragyPro 与 dragyLite 存储器不同容量(已修订)
 - [x] dragyPro GPS 备用电池供电修改为锂电池供电(已修订)
 - [ ] 插拔电池重启
 - [x] Lite 6 pin 端子 线序匹配 BetaFlight(已修订)
 - [x] 当前正在存储的文件的特殊文件名接口 “NOW”
 - [ ] 6 轴数据接入，独立传输通道测试
